### ISSUE TITLE
你好，我是新手，尝试用KJFragment+viewPager实现Fragment的嵌套效果，没有成功

### ISSUE THREAD

**Issue by iceman907** [kymjs/KJFrameForAndroid#21]
请问会不会有个实例？
KJFragment基于anroid.app.fragment 实现， 但是要实现FragmentPagerAdapter  用了android.support.v4.app.fragment,请问有什么好的建议没？

**Comment by kymjs** [comment]
使用ViewPager替换FragmentPager即可。
