### ISSUE TITLE
KJHttp

### ISSUE THREAD

**Issue by lijia008** [kymjs/KJFrameForAndroid#22]
您好，我在试用KJHttp时，在2G网络环境下请求不成功，在wifi环境下没问题。说at org.kymjs.kjframe.KJHttp.openConnection(KJHttp.java:338)有空指针异常

**Comment by kymjs** [comment]
是你网络异常。此时是捕获了空指针异常，会回调onFailure()方法

**Comment by lijia008** [comment]
嗯 谢谢
