### ISSUE TITLE
使用IntelliJ IDEA编译运行Example时报错

### ISSUE THREAD

**Issue by normalhh** [kymjs/KJFrameForAndroid#24]
Error:(132, 17) java: 无法将类 org.kymjs.kjframe.http.core.KJAsyncTask<Params,Progress,Result>中的方法 execute应用到给定类型;
  需要: capture#1, 共 ?[]
  找到: 没有参数
  原因: 形式 varargs 元素类型capture#1, 共 ?无法从 类 org.kymjs.kjframe.http.core.BarrierExecutor 进行访问

在使用SDK版本为19编译的时候。编译不通过，报了上面的Error，不知道是什么问题。

**Comment by kymjs** [comment]
本问题已经修复，使用1.41版本，请查看更新日志。
