### ISSUE TITLE
error: cannot find symbol class HttpResponse

### ISSUE THREAD

**Issue by zhongwcool** [kymjs/KJFrameForAndroid#32]
Android M上似乎移除了apache包的很多东西(不是配置问题，source中已经找不到相关内容了)，KJFrame在使用API 23编译时，已经无法编译通过了。
报错信息：
error: cannot find symbol class HttpResponse
error: cannot find symbol class Header
error: cannot find symbol class HttpEntity

**Comment by linwoain** [comment]
确实有这个问题

**Comment by kymjs** [comment]
6.0的API移除了Apache的很多包，还在解决中。

**Comment by kymjs** [comment]
从2.25开始已经支持6.0 https://github.com/kymjs/KJFrameForAndroid/releases/tag/version2.251
