### ISSUE TITLE
Android6.0中没有HttpClient，只有HttpUrlConnection了

### ISSUE THREAD

**Issue by normalhh** [kymjs/KJFrameForAndroid#33]
这种情况下，使用kjframe会不会有问题？

**Comment by kymjs** [comment]
会，不过很快就会兼容6.0了

**Comment by normalhh** [comment]
@kymjs 好的，多谢。那到时候kjframe的升级问题可能也需要您考虑进去。

**Comment by kymjs** [comment]
已经兼容https://github.com/kymjs/KJFrameForAndroid/releases/tag/version2.251
