### ISSUE TITLE
框架很好,只是当初设计BindView时怎么不参考afinal的ViewInject方法

### ISSUE THREAD

**Issue by hubs** [kymjs/KJFrameForAndroid#34]
<pre>
 //无需调用findViewById和setOnclickListener等
    @ViewInject(id=R.id.button,click="btnClick") Button button;

    public void btnClick(View v){
       textView.setText("text set form button");
    }
</pre>

现在widgetClick(View v) 所有点击 事件都需要在这里面进行switch判断 ,感觉没有afinal click="method" 这么干净清爽。个人意见..加油

**Comment by hubs** [comment]
KJBitmap kjb = KJBitmap.create(); 

这个单例怎么取消了.....

**Comment by hubs** [comment]
HttpCallBack 方法里的  onSuccess(Bitmap t)  貌似还没实现，不能用吧

**Comment by kymjs** [comment]
第一个，建议很好，会考虑加上。
第二个，应该是文档没更新吧，以[API](https://kjframe.github.io)文档为主
第三个，有实现，可以查看注释：仅在KJBitmap中可用，图片加载完成时回调
