### ISSUE TITLE
建议不使用枚举，因为枚举在安卓中会占用更多的内存

### ISSUE THREAD

**Issue by DZHound** [kymjs/KJFrameForAndroid#37]
也可能自己了解的有错误，如是错误的，请谅解

**Comment by kymjs** [comment]
是的，枚举不仅占用更多内存，而且也会生成更多的方法。只不过是很早以前开始用的了，很多旧项目中已经用了枚举类，才迫不得已保存下来的。

**Comment by kymjs** [comment]
已经修改https://github.com/kymjs/KJFrameForAndroid/releases/tag/version2.251
