### ISSUE TITLE
图片加载那部分代码感觉和 Afinal 的一样啊

### ISSUE THREAD

**Issue by MasonLiuChn** [kymjs/KJFrameForAndroid#46]

**Comment by joefei** [comment]
然后呢

**Comment by kymjs** [comment]
仅仅是类名相似而已，也许是因为图片加载的底层原理都是：
用户请求图片--->判断内存缓存--->判断本地缓存--->请求网络--->缓存至内存和磁盘
![Uploading QQ20151112-0.png…]()
  
这里是早期的KJFrame[SHA:45fd723](https://github.com/kymjs/KJFrameForAndroid/tree/45fd72343879c634b5b47088f17c30a0b58b7d9e)源码，最初的bitmap网络加载是根据郭霖翻译的[这篇文章](http://blog.csdn.net/guolin_blog/article/details/9316683)写的，后来发现一些问题，随着不断的优化与修改才有现在。    

刚看了下afinal的图片加载，afinal的原理是[（见代码FinalBitmap line 242）](https://github.com/yangfuhai/afinal/blob/master/src/net/tsz/afinal/FinalBitmap.java)使用Executors维护一个加载线程池，对于bitmap的加载逻辑是通过[BitmapProcess](https://github.com/yangfuhai/afinal/blob/master/src/net/tsz/afinal/bitmap/core/BitmapProcess.java)去判断网络图片使用下载器(Downloader)或者缓存器(BitmapCache)去加载，而本地图片则是压缩直接显示。

KJFrame是通过在[KJBitmap line 260](https://github.com/kymjs/KJFrameForAndroid/blob/master/KJFrame/kjframe/src/main/java/org/kymjs/kjframe/KJBitmap.java)中判断，网络图片使用ImageDisplayer加载，本地图片使用DiskImageRequest。而对于网络图片的加载，完全是通过KJHttp的Request请求bitmap，并加入内存缓存(磁盘缓存KJHttp已经自带了)，详见[ImageDisplayer](https://github.com/kymjs/KJFrameForAndroid/blob/master/KJFrame/kjframe/src/main/java/org/kymjs/kjframe/bitmap/ImageDisplayer.java)

而数据库部分则是使用的afinal数据库，见老版本[Readme](https://github.com/kymjs/KJFrameForAndroid/tree/45fd72343879c634b5b47088f17c30a0b58b7d9e)
